---
- hosts: baseinstall
  become: true
  tasks:
    - include: deploy/packages.yml
    - include: deploy/filesystem.yml basedir={{ "/opt" }}
    - include: deploy/npm.yml basedir={{ "/opt" }}
    - include: deploy/backup_mechaoperator.yml basedir={{ "/opt" }}
    - include: deploy/mechaoperator.yml basedir={{ "/opt" }}
    - include: deploy/helpers.yml basedir={{ "/opt" }}

