---
- hosts: baseinstall
  become: true
  tasks:
    - include: deploy/packages.yml
    - include: deploy/filesystem.yml
    - include: deploy/npm.yml
    - include: deploy/backup_mechaoperator.yml    
    - include: deploy/mechaoperator.yml
    - include: deploy/helpers.yml

