---
- hosts: mechaoperator
  become: "{{ become|default(false) }}"
  vars:
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa_vpnbox
  tasks:
    # assume packages is done - we aren't root
    # - include: deploy/packages.yml
    - include: deploy/filesystem.yml
    - include: deploy/npm.yml
    - include: deploy/backup_mechaoperator.yml
    - include: deploy/mechaoperator.yml
    - include: deploy/helpers.yml
