---
- name: load secrets
  include_vars: "deploy/backup_secrets.yml"
  no_log: true
- name: copy ssh private key
  template:
    src: src/etc/ssh/backup_id_rsa.j2
    dest: /opt/futel/etc/ssh/backup_id_rsa
- name: update ssh private key perms
  file:
    path: /opt/futel/etc/ssh/backup_id_rsa
    mode: "go-r"
- name: copy backup src
  copy:
    src: src/bin
    dest: /opt/futel
- name: make backup script executable
  file:
    path: "{{ item }}"
    mode: "u+x"
  with_items:
    - /opt/futel/bin/backup_backupbox.sh
- name: create cron job
  cron:
    name: "prod backup"
    minute: "*/5"
    job: /opt/futel/bin/backup_backupbox.sh
