---
- name: set up filesystem
  file:
    path: "{{ basedir }}/{{ item }}"
    state: directory
  with_items:
    - futel/src
    - futel/bin
    - futel/etc
    - futel/etc/ssh
    - futel/var
    - futel/var/log    
    - futel/var/spool
    - futel/var/spool/backups
    - futel/var/spool/backups/prod
    - futel/var/spool/stats    
    - futel/var/spool/stats/prod
    - futel/var/tmp
    