---
# distro package setup and installation
- name: update yum
  yum:
    name: "*"
    state: latest
- name: install epel-release yum package
  yum:
    name: epel-release
    state: present
- name: install yum packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:    
    - gcc-c++
    - supervisor  
    - nodejs

