---
- name: copy epel rpm
  copy:
    src: src/epel-release-latest-7.noarch.rpm 
    dest: /tmp/epel-release-latest-7.noarch.rpm 
- name: install epel rpm
  yum:
    name: /tmp/epel-release-latest-7.noarch.rpm
    state: present
- name: install yum packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - supervisor  
    - nodejs
